//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace cmsis_svd
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class device {

        private string vendorField;

        private string vendorIDField;

        private string nameField;

        private string seriesField;

        private string versionField;

        private string descriptionField;

        private string licenseTextField;

        private cpuType cpuField;

        private string headerSystemFilenameField;

        private string headerDefinitionsPrefixField;

        private string addressUnitBitsField;

        private string widthField;

        private string sizeField;

        private accessType accessField;

        private bool accessFieldSpecified;

        private string protectionField;

        private string resetValueField;

        private string resetMaskField;

        private peripheralType[] peripheralsField;

        private deviceVendorExtensions vendorExtensionsField;

        private decimal schemaVersionField;

        /// <remarks/>
        public string vendor {
            get {
                return this.vendorField;
            }
            set {
                this.vendorField = value;
            }
        }

        /// <remarks/>
        public string vendorID {
            get {
                return this.vendorIDField;
            }
            set {
                this.vendorIDField = value;
            }
        }

        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string series {
            get {
                return this.seriesField;
            }
            set {
                this.seriesField = value;
            }
        }

        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }

        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string licenseText {
            get {
                return this.licenseTextField;
            }
            set {
                this.licenseTextField = value;
            }
        }

        /// <remarks/>
        public cpuType cpu {
            get {
                return this.cpuField;
            }
            set {
                this.cpuField = value;
            }
        }

        /// <remarks/>
        public string headerSystemFilename {
            get {
                return this.headerSystemFilenameField;
            }
            set {
                this.headerSystemFilenameField = value;
            }
        }

        /// <remarks/>
        public string headerDefinitionsPrefix {
            get {
                return this.headerDefinitionsPrefixField;
            }
            set {
                this.headerDefinitionsPrefixField = value;
            }
        }

        /// <remarks/>
        public string addressUnitBits {
            get {
                return this.addressUnitBitsField;
            }
            set {
                this.addressUnitBitsField = value;
            }
        }

        /// <remarks/>
        public string width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }

        /// <remarks/>
        public string size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }

        /// <remarks/>
        public accessType access {
            get {
                return this.accessField;
            }
            set {
                this.accessField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool accessSpecified {
            get {
                return this.accessFieldSpecified;
            }
            set {
                this.accessFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string protection {
            get {
                return this.protectionField;
            }
            set {
                this.protectionField = value;
            }
        }

        /// <remarks/>
        public string resetValue {
            get {
                return this.resetValueField;
            }
            set {
                this.resetValueField = value;
            }
        }

        /// <remarks/>
        public string resetMask {
            get {
                return this.resetMaskField;
            }
            set {
                this.resetMaskField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("peripheral", IsNullable = false)]
        public peripheralType[] peripherals {
            get {
                return this.peripheralsField;
            }
            set {
                this.peripheralsField = value;
            }
        }

        /// <remarks/>
        public deviceVendorExtensions vendorExtensions {
            get {
                return this.vendorExtensionsField;
            }
            set {
                this.vendorExtensionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public decimal schemaVersion {
            get {
                return this.schemaVersionField;
            }
            set {
                this.schemaVersionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cpuType {

        private cpuNameType nameField;

        private string revisionField;

        private endianType endianField;

        private bool mpuPresentField;

        private bool fpuPresentField;

        private bool fpuDPField;

        private bool fpuDPFieldSpecified;

        private bool icachePresentField;

        private bool icachePresentFieldSpecified;

        private bool dcachePresentField;

        private bool dcachePresentFieldSpecified;

        private bool itcmPresentField;

        private bool itcmPresentFieldSpecified;

        private bool dtcmPresentField;

        private bool dtcmPresentFieldSpecified;

        private bool vtorPresentField;

        private bool vtorPresentFieldSpecified;

        private string nvicPrioBitsField;

        private bool vendorSystickConfigField;

        private string deviceNumInterruptsField;

        private string sauNumRegionsField;

        private cpuTypeSauRegionsConfig sauRegionsConfigField;

        /// <remarks/>
        public cpuNameType name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string revision {
            get {
                return this.revisionField;
            }
            set {
                this.revisionField = value;
            }
        }

        /// <remarks/>
        public endianType endian {
            get {
                return this.endianField;
            }
            set {
                this.endianField = value;
            }
        }

        /// <remarks/>
        public bool mpuPresent {
            get {
                return this.mpuPresentField;
            }
            set {
                this.mpuPresentField = value;
            }
        }

        /// <remarks/>
        public bool fpuPresent {
            get {
                return this.fpuPresentField;
            }
            set {
                this.fpuPresentField = value;
            }
        }

        /// <remarks/>
        public bool fpuDP {
            get {
                return this.fpuDPField;
            }
            set {
                this.fpuDPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fpuDPSpecified {
            get {
                return this.fpuDPFieldSpecified;
            }
            set {
                this.fpuDPFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool icachePresent {
            get {
                return this.icachePresentField;
            }
            set {
                this.icachePresentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool icachePresentSpecified {
            get {
                return this.icachePresentFieldSpecified;
            }
            set {
                this.icachePresentFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool dcachePresent {
            get {
                return this.dcachePresentField;
            }
            set {
                this.dcachePresentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dcachePresentSpecified {
            get {
                return this.dcachePresentFieldSpecified;
            }
            set {
                this.dcachePresentFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool itcmPresent {
            get {
                return this.itcmPresentField;
            }
            set {
                this.itcmPresentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool itcmPresentSpecified {
            get {
                return this.itcmPresentFieldSpecified;
            }
            set {
                this.itcmPresentFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool dtcmPresent {
            get {
                return this.dtcmPresentField;
            }
            set {
                this.dtcmPresentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dtcmPresentSpecified {
            get {
                return this.dtcmPresentFieldSpecified;
            }
            set {
                this.dtcmPresentFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool vtorPresent {
            get {
                return this.vtorPresentField;
            }
            set {
                this.vtorPresentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vtorPresentSpecified {
            get {
                return this.vtorPresentFieldSpecified;
            }
            set {
                this.vtorPresentFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string nvicPrioBits {
            get {
                return this.nvicPrioBitsField;
            }
            set {
                this.nvicPrioBitsField = value;
            }
        }

        /// <remarks/>
        public bool vendorSystickConfig {
            get {
                return this.vendorSystickConfigField;
            }
            set {
                this.vendorSystickConfigField = value;
            }
        }

        /// <remarks/>
        public string deviceNumInterrupts {
            get {
                return this.deviceNumInterruptsField;
            }
            set {
                this.deviceNumInterruptsField = value;
            }
        }

        /// <remarks/>
        public string sauNumRegions {
            get {
                return this.sauNumRegionsField;
            }
            set {
                this.sauNumRegionsField = value;
            }
        }

        /// <remarks/>
        public cpuTypeSauRegionsConfig sauRegionsConfig {
            get {
                return this.sauRegionsConfigField;
            }
            set {
                this.sauRegionsConfigField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum cpuNameType {

        /// <remarks/>
        CM0,

        /// <remarks/>
        CM0PLUS,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CM0+")]
        CM01,

        /// <remarks/>
        CM1,

        /// <remarks/>
        SC000,

        /// <remarks/>
        CM3,

        /// <remarks/>
        SC300,

        /// <remarks/>
        CM4,

        /// <remarks/>
        CM7,

        /// <remarks/>
        CA5,

        /// <remarks/>
        CA7,

        /// <remarks/>
        CA8,

        /// <remarks/>
        CA9,

        /// <remarks/>
        CA15,

        /// <remarks/>
        CA17,

        /// <remarks/>
        CA53,

        /// <remarks/>
        CA57,

        /// <remarks/>
        CA72,

        /// <remarks/>
        other,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum endianType {

        /// <remarks/>
        little,

        /// <remarks/>
        big,

        /// <remarks/>
        selectable,

        /// <remarks/>
        other,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class cpuTypeSauRegionsConfig {

        private cpuTypeSauRegionsConfigRegion[] regionField;

        private bool enabledField;

        private string protectionWhenDisabledField;

        public cpuTypeSauRegionsConfig() {
            this.enabledField = true;
            this.protectionWhenDisabledField = "s";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("region")]
        public cpuTypeSauRegionsConfigRegion[] region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute("s")]
        public string protectionWhenDisabled {
            get {
                return this.protectionWhenDisabledField;
            }
            set {
                this.protectionWhenDisabledField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class cpuTypeSauRegionsConfigRegion {

        private string[] baseField;

        private string[] limitField;

        private string[] accessField;

        private bool enabledField;

        private string nameField;

        public cpuTypeSauRegionsConfigRegion() {
            this.enabledField = true;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("base")]
        public string[] @base {
            get {
                return this.baseField;
            }
            set {
                this.baseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("limit")]
        public string[] limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("access")]
        public string[] access {
            get {
                return this.accessField;
            }
            set {
                this.accessField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enumeratedValuesType {

        private string nameField;

        private enumUsageType usageField;

        private bool usageFieldSpecified;

        private enumeratedValuesTypeEnumeratedValue[] enumeratedValueField;

        private string derivedFromField;

        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public enumUsageType usage {
            get {
                return this.usageField;
            }
            set {
                this.usageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usageSpecified {
            get {
                return this.usageFieldSpecified;
            }
            set {
                this.usageFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("enumeratedValue")]
        public enumeratedValuesTypeEnumeratedValue[] enumeratedValue {
            get {
                return this.enumeratedValueField;
            }
            set {
                this.enumeratedValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string derivedFrom {
            get {
                return this.derivedFromField;
            }
            set {
                this.derivedFromField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum enumUsageType {

        /// <remarks/>
        read,

        /// <remarks/>
        write,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("read-write")]
        readwrite,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class enumeratedValuesTypeEnumeratedValue {

        private string nameField;

        private string descriptionField;

        private object itemField;

        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("isDefault", typeof(bool))]
        [System.Xml.Serialization.XmlElementAttribute("value", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fieldType {

        private string nameField;

        private string descriptionField;

        private string[] itemsField;

        private ItemsChoiceType[] itemsElementNameField;

        private accessType accessField;

        private bool accessFieldSpecified;

        private modifiedWriteValuesType modifiedWriteValuesField;

        private bool modifiedWriteValuesFieldSpecified;

        private writeConstraintType writeConstraintField;

        private readActionType readActionField;

        private bool readActionFieldSpecified;

        private enumeratedValuesType[] enumeratedValuesField;

        private string derivedFromField;

        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bitOffset", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("bitRange", typeof(string), DataType = "token")]
        [System.Xml.Serialization.XmlElementAttribute("bitWidth", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("lsb", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("msb", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public string[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }

        /// <remarks/>
        public accessType access {
            get {
                return this.accessField;
            }
            set {
                this.accessField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool accessSpecified {
            get {
                return this.accessFieldSpecified;
            }
            set {
                this.accessFieldSpecified = value;
            }
        }

        /// <remarks/>
        public modifiedWriteValuesType modifiedWriteValues {
            get {
                return this.modifiedWriteValuesField;
            }
            set {
                this.modifiedWriteValuesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modifiedWriteValuesSpecified {
            get {
                return this.modifiedWriteValuesFieldSpecified;
            }
            set {
                this.modifiedWriteValuesFieldSpecified = value;
            }
        }

        /// <remarks/>
        public writeConstraintType writeConstraint {
            get {
                return this.writeConstraintField;
            }
            set {
                this.writeConstraintField = value;
            }
        }

        /// <remarks/>
        public readActionType readAction {
            get {
                return this.readActionField;
            }
            set {
                this.readActionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool readActionSpecified {
            get {
                return this.readActionFieldSpecified;
            }
            set {
                this.readActionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("enumeratedValues")]
        public enumeratedValuesType[] enumeratedValues {
            get {
                return this.enumeratedValuesField;
            }
            set {
                this.enumeratedValuesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string derivedFrom {
            get {
                return this.derivedFromField;
            }
            set {
                this.derivedFromField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
    public enum ItemsChoiceType {

        /// <remarks/>
        bitOffset,

        /// <remarks/>
        bitRange,

        /// <remarks/>
        bitWidth,

        /// <remarks/>
        lsb,

        /// <remarks/>
        msb,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum accessType {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("read-only")]
        @readonly,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("write-only")]
        writeonly,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("read-write")]
        readwrite,

        /// <remarks/>
        writeOnce,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("read-writeOnce")]
        readwriteOnce,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum modifiedWriteValuesType {

        /// <remarks/>
        oneToClear,

        /// <remarks/>
        oneToSet,

        /// <remarks/>
        oneToToggle,

        /// <remarks/>
        zeroToClear,

        /// <remarks/>
        zeroToSet,

        /// <remarks/>
        zeroToToggle,

        /// <remarks/>
        clear,

        /// <remarks/>
        set,

        /// <remarks/>
        modify,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class writeConstraintType {

        private object itemField;

        private ItemChoiceType1 itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("range", typeof(writeConstraintTypeRange))]
        [System.Xml.Serialization.XmlElementAttribute("useEnumeratedValues", typeof(bool))]
        [System.Xml.Serialization.XmlElementAttribute("writeAsRead", typeof(bool))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class writeConstraintTypeRange {

        private string minimumField;

        private string maximumField;

        /// <remarks/>
        public string minimum {
            get {
                return this.minimumField;
            }
            set {
                this.minimumField = value;
            }
        }

        /// <remarks/>
        public string maximum {
            get {
                return this.maximumField;
            }
            set {
                this.maximumField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
    public enum ItemChoiceType1 {

        /// <remarks/>
        range,

        /// <remarks/>
        useEnumeratedValues,

        /// <remarks/>
        writeAsRead,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum readActionType {

        /// <remarks/>
        clear,

        /// <remarks/>
        set,

        /// <remarks/>
        modify,

        /// <remarks/>
        modifyExternal,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registerType {

        private string dimField;

        private string dimIncrementField;

        private string dimIndexField;

        private string nameField;

        private string displayNameField;

        private string descriptionField;

        private string itemField;

        private ItemChoiceType itemElementNameField;

        private string addressOffsetField;

        private string sizeField;

        private accessType accessField;

        private bool accessFieldSpecified;

        private string protectionField;

        private string resetValueField;

        private string resetMaskField;

        private dataTypeType dataTypeField;

        private bool dataTypeFieldSpecified;

        private modifiedWriteValuesType modifiedWriteValuesField;

        private bool modifiedWriteValuesFieldSpecified;

        private writeConstraintType writeConstraintField;

        private readActionType readActionField;

        private bool readActionFieldSpecified;

        private fieldType[] fieldsField;

        private string derivedFromField;

        /// <remarks/>
        public string dim {
            get {
                return this.dimField;
            }
            set {
                this.dimField = value;
            }
        }

        /// <remarks/>
        public string dimIncrement {
            get {
                return this.dimIncrementField;
            }
            set {
                this.dimIncrementField = value;
            }
        }

        /// <remarks/>
        public string dimIndex {
            get {
                return this.dimIndexField;
            }
            set {
                this.dimIndexField = value;
            }
        }

        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string displayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }

        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("alternateGroup", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("alternateRegister", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }

        /// <remarks/>
        public string addressOffset {
            get {
                return this.addressOffsetField;
            }
            set {
                this.addressOffsetField = value;
            }
        }

        /// <remarks/>
        public string size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }

        /// <remarks/>
        public accessType access {
            get {
                return this.accessField;
            }
            set {
                this.accessField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool accessSpecified {
            get {
                return this.accessFieldSpecified;
            }
            set {
                this.accessFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string protection {
            get {
                return this.protectionField;
            }
            set {
                this.protectionField = value;
            }
        }

        /// <remarks/>
        public string resetValue {
            get {
                return this.resetValueField;
            }
            set {
                this.resetValueField = value;
            }
        }

        /// <remarks/>
        public string resetMask {
            get {
                return this.resetMaskField;
            }
            set {
                this.resetMaskField = value;
            }
        }

        /// <remarks/>
        public dataTypeType dataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataTypeSpecified {
            get {
                return this.dataTypeFieldSpecified;
            }
            set {
                this.dataTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public modifiedWriteValuesType modifiedWriteValues {
            get {
                return this.modifiedWriteValuesField;
            }
            set {
                this.modifiedWriteValuesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modifiedWriteValuesSpecified {
            get {
                return this.modifiedWriteValuesFieldSpecified;
            }
            set {
                this.modifiedWriteValuesFieldSpecified = value;
            }
        }

        /// <remarks/>
        public writeConstraintType writeConstraint {
            get {
                return this.writeConstraintField;
            }
            set {
                this.writeConstraintField = value;
            }
        }

        /// <remarks/>
        public readActionType readAction {
            get {
                return this.readActionField;
            }
            set {
                this.readActionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool readActionSpecified {
            get {
                return this.readActionFieldSpecified;
            }
            set {
                this.readActionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("field", IsNullable = false)]
        public fieldType[] fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string derivedFrom {
            get {
                return this.derivedFromField;
            }
            set {
                this.derivedFromField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
    public enum ItemChoiceType {

        /// <remarks/>
        alternateGroup,

        /// <remarks/>
        alternateRegister,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum dataTypeType {

        /// <remarks/>
        uint8_t,

        /// <remarks/>
        uint16_t,

        /// <remarks/>
        uint32_t,

        /// <remarks/>
        uint64_t,

        /// <remarks/>
        int8_t,

        /// <remarks/>
        int16_t,

        /// <remarks/>
        int32_t,

        /// <remarks/>
        int64_t,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("uint8_t *")]
        uint8_t1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("uint16_t *")]
        uint16_t1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("uint32_t *")]
        uint32_t1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("uint64_t *")]
        uint64_t1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("int8_t *")]
        int8_t1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("int16_t *")]
        int16_t1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("int32_t *")]
        int32_t1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("int64_t *")]
        int64_t1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class clusterType {

        private string dimField;

        private string dimIncrementField;

        private string dimIndexField;

        private string nameField;

        private string descriptionField;

        private string alternateClusterField;

        private string headerStructNameField;

        private string addressOffsetField;

        private string sizeField;

        private accessType accessField;

        private bool accessFieldSpecified;

        private string protectionField;

        private string resetValueField;

        private string resetMaskField;

        private object[] itemsField;

        private string derivedFromField;

        /// <remarks/>
        public string dim {
            get {
                return this.dimField;
            }
            set {
                this.dimField = value;
            }
        }

        /// <remarks/>
        public string dimIncrement {
            get {
                return this.dimIncrementField;
            }
            set {
                this.dimIncrementField = value;
            }
        }

        /// <remarks/>
        public string dimIndex {
            get {
                return this.dimIndexField;
            }
            set {
                this.dimIndexField = value;
            }
        }

        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string alternateCluster {
            get {
                return this.alternateClusterField;
            }
            set {
                this.alternateClusterField = value;
            }
        }

        /// <remarks/>
        public string headerStructName {
            get {
                return this.headerStructNameField;
            }
            set {
                this.headerStructNameField = value;
            }
        }

        /// <remarks/>
        public string addressOffset {
            get {
                return this.addressOffsetField;
            }
            set {
                this.addressOffsetField = value;
            }
        }

        /// <remarks/>
        public string size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }

        /// <remarks/>
        public accessType access {
            get {
                return this.accessField;
            }
            set {
                this.accessField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool accessSpecified {
            get {
                return this.accessFieldSpecified;
            }
            set {
                this.accessFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string protection {
            get {
                return this.protectionField;
            }
            set {
                this.protectionField = value;
            }
        }

        /// <remarks/>
        public string resetValue {
            get {
                return this.resetValueField;
            }
            set {
                this.resetValueField = value;
            }
        }

        /// <remarks/>
        public string resetMask {
            get {
                return this.resetMaskField;
            }
            set {
                this.resetMaskField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cluster", typeof(clusterType))]
        [System.Xml.Serialization.XmlElementAttribute("register", typeof(registerType))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string derivedFrom {
            get {
                return this.derivedFromField;
            }
            set {
                this.derivedFromField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class interruptType {

        private string nameField;

        private string descriptionField;

        private string valueField;

        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addressBlockType {

        private string offsetField;

        private string sizeField;

        private addressBlockTypeUsage usageField;

        private string protectionField;

        /// <remarks/>
        public string offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }

        /// <remarks/>
        public string size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }

        /// <remarks/>
        public addressBlockTypeUsage usage {
            get {
                return this.usageField;
            }
            set {
                this.usageField = value;
            }
        }

        /// <remarks/>
        public string protection {
            get {
                return this.protectionField;
            }
            set {
                this.protectionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum addressBlockTypeUsage {

        /// <remarks/>
        registers,

        /// <remarks/>
        buffer,

        /// <remarks/>
        reserved,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class peripheralType {

        private string dimField;

        private string dimIncrementField;

        private string dimIndexField;

        private string nameField;

        private string versionField;

        private string descriptionField;

        private string alternatePeripheralField;

        private string groupNameField;

        private string prependToNameField;

        private string appendToNameField;

        private string headerStructNameField;

        private string disableConditionField;

        private string baseAddressField;

        private string sizeField;

        private accessType accessField;

        private bool accessFieldSpecified;

        private string protectionField;

        private string resetValueField;

        private string resetMaskField;

        private addressBlockType[] addressBlockField;

        private interruptType[] interruptField;

        private object[] registersField;

        private string derivedFromField;

        /// <remarks/>
        public string dim {
            get {
                return this.dimField;
            }
            set {
                this.dimField = value;
            }
        }

        /// <remarks/>
        public string dimIncrement {
            get {
                return this.dimIncrementField;
            }
            set {
                this.dimIncrementField = value;
            }
        }

        /// <remarks/>
        public string dimIndex {
            get {
                return this.dimIndexField;
            }
            set {
                this.dimIndexField = value;
            }
        }

        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }

        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string alternatePeripheral {
            get {
                return this.alternatePeripheralField;
            }
            set {
                this.alternatePeripheralField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "Name")]
        public string groupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
            }
        }

        /// <remarks/>
        public string prependToName {
            get {
                return this.prependToNameField;
            }
            set {
                this.prependToNameField = value;
            }
        }

        /// <remarks/>
        public string appendToName {
            get {
                return this.appendToNameField;
            }
            set {
                this.appendToNameField = value;
            }
        }

        /// <remarks/>
        public string headerStructName {
            get {
                return this.headerStructNameField;
            }
            set {
                this.headerStructNameField = value;
            }
        }

        /// <remarks/>
        public string disableCondition {
            get {
                return this.disableConditionField;
            }
            set {
                this.disableConditionField = value;
            }
        }

        /// <remarks/>
        public string baseAddress {
            get {
                return this.baseAddressField;
            }
            set {
                this.baseAddressField = value;
            }
        }

        /// <remarks/>
        public string size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }

        /// <remarks/>
        public accessType access {
            get {
                return this.accessField;
            }
            set {
                this.accessField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool accessSpecified {
            get {
                return this.accessFieldSpecified;
            }
            set {
                this.accessFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string protection {
            get {
                return this.protectionField;
            }
            set {
                this.protectionField = value;
            }
        }

        /// <remarks/>
        public string resetValue {
            get {
                return this.resetValueField;
            }
            set {
                this.resetValueField = value;
            }
        }

        /// <remarks/>
        public string resetMask {
            get {
                return this.resetMaskField;
            }
            set {
                this.resetMaskField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("addressBlock")]
        public addressBlockType[] addressBlock {
            get {
                return this.addressBlockField;
            }
            set {
                this.addressBlockField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("interrupt")]
        public interruptType[] interrupt {
            get {
                return this.interruptField;
            }
            set {
                this.interruptField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("cluster", typeof(clusterType), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("register", typeof(registerType), IsNullable = false)]
        public object[] registers {
            get {
                return this.registersField;
            }
            set {
                this.registersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string derivedFrom {
            get {
                return this.derivedFromField;
            }
            set {
                this.derivedFromField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class deviceVendorExtensions {

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
}
